package router

import (
	"net/http"

	prstatroutes "github.com/R-V-S/prstats/constructs/abstract/prstat/routes"
	_ "github.com/R-V-S/prstats/docs" // docs are generated by Swag CLI
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	echoSwagger "github.com/swaggo/echo-swagger"
)

// NewRouter ...
func NewRouter() http.Handler {
	router := echo.New()

	router.Use(middleware.Logger())
	router.Use(middleware.Recover())

	router.GET("/", func(c echo.Context) error {
		return c.String(http.StatusOK, "prstats REST API!")
	})

	prstatroutes.Routes(router)

	router.GET("/docs/*", echoSwagger.WrapHandler)

	return router
}
